### ISSUE TITLE
About Pre Release (v1.4pr5)

### ISSUE THREAD

**Issue by AlinaNikitina93** [ColonolNutty/Sims4ControlMenu#1]
Hi there! The readme says there should be a controlmenu.ts4script file, but there isn't one in the pre-release folder. Where can I get it?

**Comment by AlinaNikitina93** [comment]
Okay, I just compiled it :)

**Comment by ColonolNutty** [comment]
The pre release is available in my discord currently. It also requires the pre release of S4CL (which is also available in my discord)
https://discord.gg/fdCgyXkDZb
